server:
  port: 0

spring:
  application:
    name: movieService
  # PostgreSql Properties
  datasource:
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:cine_vision}
    password: ${POSTGRES_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
    # HikariCP Connection Pool Configuration
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      leak-detection-threshold: 60000
      pool-name: CineVisionMovieServiceCP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
        jdbc:
          '[batch_size]': 25
        '[order_inserts]': true
        '[order_updates]': true
    hibernate:
      ddl-auto: validate # Changed from update to validate for Flyway
    show-sql: false # Disable in production
  # Apache Kafka Producer Properties
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.kaankaplan.movieService.entity.dto.EmailMessageKafkaDto
    topic:
      name: email_topics
  # Zipkin Properties
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411
  # Sleuth Properties
  sleuth:
    sampler:
      probability: 1.0
# Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Circuit Breaker Properties
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  server:
    port: 8000
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s